### PR TITLE
fix starting of tomcat, quiet down unzip to reduce log polution, and …

### PR DESCRIPTION
**Pull request by misev**

### CODE REVIEW

**Comment by kalxas** [comment]
Tomcat needs to stop at the end of the script.

The reason that service start does not work is that we are in a chroot while making the iso.

**Comment by misev** [comment]
I was guessing it's because of the chroot, it's just surprising that it worked fine in the previous versions.
Tomcat will be stopped now at the end.

**Comment by kalxas** [comment]
Yes that is surprising, chroot now ignores all systemctl calls. Used to work in 18.04...
Thanks for the update, I will test later today and merge

**Comment by kalxas** [comment]
http://aiolos.survey.ntua.gr/gisvm/dev/osgeolive-nightly-build190-amd64-9db2bd5-rasdaman.iso

http://aiolos.survey.ntua.gr/gisvm/dev/osgeolive-nightly-build190-amd64-9db2bd5-rasdaman-log.tar.gz

**Comment by kalxas** [comment]
I was just checking the build logs and I realized that the installer uses pip to install python packages.

```
    "9 INFO": "Installing python packages with pip3: setuptools... ",
    "10 pip3 install setuptools": {
        "out": "Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (45.2.0)
",
        "err": "",
        "code": 0,
        "user": "root",
        "start_time": "2020-12-17 18:52:58",
        "execution_time": 1.4275622367858887
    },
    "11 INFO": "Python packages installed successfully.",
    "12 INFO": "Installing python packages with pip3: jsonschema python-dateutil lxml GDAL==3.0.4... ",
    "13 pip3 install jsonschema python-dateutil lxml GDAL==3.0.4": {
        "out": "Requirement already satisfied: jsonschema in /usr/lib/python3/dist-packages (3.2.0)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (2.7.3)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (4.5.0)
Collecting GDAL==3.0.4
  Downloading GDAL-3.0.4.tar.gz (577 kB)
Building wheels for collected packages: GDAL
  Building wheel for GDAL (setup.py): started
  Building wheel for GDAL (setup.py): finished with status 'done'
  Created wheel for GDAL: filename=GDAL-3.0.4-cp38-cp38-linux_x86_64.whl size=2684445 sha256=e0cd4cff484e5bc8d948f068fda82d840da8390d938d3de59045c92255d7ea40
  Stored in directory: /root/.cache/pip/wheels/38/c9/11/d2e0d47aa4f5035370eee7faf53105388f01cb567d1cc5a73d
Successfully built GDAL
Installing collected packages: GDAL
  Attempting uninstall: GDAL
    Found existing installation: GDAL 3.1.3
    Not uninstalling gdal at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'GDAL'. No files were found to uninstall.
Successfully installed GDAL-3.0.4
",
        "err": "",
        "code": 0,
        "user": "root",
        "start_time": "2020-12-17 18:52:59",
        "execution_time": 35.61421608924866
    },
    "14 INFO": "Python packages installed successfully.",
```

Use of pip is not permitted, we are only installing python packages in deb format.
Can you please list the python packages you need in the disk?

**Comment by kalxas** [comment]
More specifically, the installer should use GDAL included in the ppa (3.2.0) and not pull GDAL 3.0.3 from Pypi.

**Comment by misev** [comment]
The latest commit fixes the dependencies issue (nothing is installed anymore, neither with apt-get nor pip3).
It also fixes the libgdal-java issue caused by https://trac.osgeo.org/osgeolive/ticket/2288

**Comment by kalxas** [comment]
Thanks @misev I will make a new iso to test and let you know

**Comment by kalxas** [comment]
http://aiolos.survey.ntua.gr/gisvm/dev/osgeolive-nightly-build193-amd64-4927958-rasdaman-log.tar.gz

http://aiolos.survey.ntua.gr/gisvm/dev/osgeolive-nightly-build193-amd64-4927958-rasdaman.iso

**Comment by misev** [comment]
I checked it, it works well.

**Comment by kalxas** [comment]
thanks, merging now

**Pull request merged**
