### PR TITLE
adding shared files for ossimplanet

### PR DESCRIPTION
**Pull request by epifanio**

### CODE REVIEW

**Comment by kalxas** [comment]
Why do we need to add those files?
Shouldn't they be part of the ossim distribution?

**Comment by epifanio** [comment]
Are thei in any package? those files are from the OSSIM src code repository. Either we install them this way or we make a ossim-share.deb package.

**Comment by kalxas** [comment]
thanks @epifanio for the feedback.

**Comment by epifanio** [comment]
is it going to be merged or solved in other ways? I need this to work on the ossimplanet quickstart.

**Comment by kalxas** [comment]
Doing a test build right now

**Comment by kalxas** [comment]
merged.

**Pull request closed without merging**
