### PR TITLE
Add tribute to Malena to the welcome message

### PR DESCRIPTION
**Pull request by Bakaniko**
@astroidex, please comment (can you ping Enoch I don't remind his handler?)

### CODE REVIEW

**Comment by kalxas** [comment]
I would try to make this shorter, like:

We would like to dedicate this version to our friend Malena Libman who passed away shortly before OSGeoLive 14.0 was released.

**Review by kalxas — APPROVED** [review]

**Comment by kalxas** [comment]
If others prefer the longer version, I would need to probably make the other parts of the message shorter (actually we can also cut from the language setup text since we do not pre-load all the ubuntu language files in the iso due to space restrictions)

**Review by astroidex — COMMENTED** [review]
Welcome to OSGeoLive 14.0 - "Malena"

- instead of .

**Review by astroidex — COMMENTED** [review]
I like the long version. Maybe like this it would be ok? But I am also fine with the short version.

We would like to dedicate this version to our friend Malena Libman 
who passed away shortly before OSGeoLive 14.0 was released. FOSS4G 2021 Buenos Aires was her dream. 
Farewell Malena, we will miss you.

**Comment by kalxas** [comment]
+1 to the changes Astrid proposed and the long version.
@Bakaniko can you please update?

**Pull request merged**
