### PR TITLE
Upgrade GeoNetwork to 3.2.1

### PR DESCRIPTION
**Pull request by PascalLike**
Here the changes needed for upgrading GeoNetwork to 3.2.1. For the time being, I only updated the software part. Now I will also deal with the documentation. Thanks

### CODE REVIEW

**Comment by kalxas** [comment]
Hi @PascalLike 
Can you please send an e-mail to the osgeolive mailing list accepting the contribution agreement?
See example here: https://lists.osgeo.org/pipermail/live-demo/2016-August/011632.html
More details here: https://wiki.osgeo.org/wiki/Live_GIS_Disc#Git_migration

**Comment by kalxas** [comment]
I have tried this PR in the latest build and the startup script is not working for me.
Here is the geonetwork part of the logs:
```
===============================================================
Starting "install_geonetwork.sh" ...
===============================================================
--2017-05-08 13:28:47--  https://sourceforge.net/projects/geonetwork/files/GeoNetwork_unstable_development_versions/v3.2.1/geonetwork-install-3.2.1-0.jar/download
Resolving sourceforge.net (sourceforge.net)... 216.34.181.60
Connecting to sourceforge.net (sourceforge.net)|216.34.181.60|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-05-08 13:28:48 ERROR 404: Not Found.

START copy of files.
'/usr/local/share/gisvm/bin/../app-conf/geonetwork/install.xml' -> './install.xml'
'/usr/local/share/gisvm/bin/../app-conf/geonetwork/jetty.xml' -> './jetty.xml'
'/usr/local/share/gisvm/bin/../app-conf/geonetwork/startup.sh' -> './startup.sh'
'/usr/local/share/gisvm/bin/../app-conf/geonetwork/shutdown.sh' -> './shutdown.sh'
'/usr/local/share/gisvm/bin/../app-conf/geonetwork/data-db-default.sql' -> './data-db-default.sql'
END copy of files.
SHUTDOWN
START jar installation.
Error: Invalid or corrupt jarfile geonetwork-install-3.2.1-0.jar
END jar installation.
cp: cannot create regular file '/usr/local/lib/geonetwork/jetty/etc/jetty.xml': No such file or directory
cp: cannot create regular file '/usr/local/lib/geonetwork/web/geonetwork/WEB-INF/classes/setup/sql/data/.': No such file or directory
cp: cannot create regular file '/usr/local/lib/geonetwork/bin/startup.sh': No such file or directory
cp: cannot create regular file '/usr/local/lib/geonetwork/bin/shutdown.sh': No such file or directory
chgrp: cannot access '/usr/local/lib/geonetwork/jetty': No such file or directory
chgrp: cannot access '/usr/local/lib/geonetwork/jetty/logs': No such file or directory
chgrp: cannot access '/usr/local/lib/geonetwork/web/geonetwork/WEB-INF/': No such file or directory
chgrp: cannot access '/usr/local/lib/geonetwork/web/geonetwork/images/logos': No such file or directory
chmod: cannot access '/usr/local/lib/geonetwork/jetty': No such file or directory
chmod: cannot access '/usr/local/lib/geonetwork/jetty/logs': No such file or directory
chmod: cannot access '/usr/local/lib/geonetwork/web/geonetwork/WEB-INF/': No such file or directory
chmod: cannot access '/usr/local/lib/geonetwork/web/geonetwork/images/logos': No such file or directory
The user `user' is already a member of `users'.
'/usr/local/share/gisvm/bin/../app-conf/geonetwork/start_geonetwork.desktop' -> './start_geonetwork.desktop'
'/usr/local/share/gisvm/bin/../app-conf/geonetwork/stop_geonetwork.desktop' -> './stop_geonetwork.desktop'
'/usr/local/share/gisvm/bin/../app-conf/geonetwork/geonetwork.desktop' -> './geonetwork.desktop'
--2017-05-08 13:28:48--  https://github.com/OSGeo/OSGeoLive-doc/raw/master/images/project_logos/logo-GeoNetwork.png
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/OSGeo/OSGeoLive-doc/master/images/project_logos/logo-GeoNetwork.png [following]
--2017-05-08 13:28:49--  https://raw.githubusercontent.com/OSGeo/OSGeoLive-doc/master/images/project_logos/logo-GeoNetwork.png
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7004 (6.8K) [image/png]
Saving to: 'geonetwork_icon.png'

     0K                                                      100% 85.9M=0s

2017-05-08 13:28:49 (85.9 MB/s) - 'geonetwork_icon.png' saved [7004/7004]

===============================================================
Finished "install_geonetwork.sh"
Disk Usage1: install_geonetwork.sh,Filesystem,1K-blocks,Used,Available,Use%,Mounted_on,date
Disk Usage2: install_geonetwork.sh,-,36157,12640,21658,37%,/,2017-05-08 13:28:49+00:00
Temp Usage: install_geonetwork.sh,290	/tmp
===============================================================
```

**Comment by PascalLike** [comment]
Sorry @kalxas, please try now. There was a small typo. I changed the url for download at the last minute. 

I sent the email (Antonio) and I'm going to also pull the request to have my name on contributors list.

**Comment by kalxas** [comment]
Thanks Antonio, I will try again.

**Comment by kalxas** [comment]
Tested on latest nightly and works fine (only the top left icon is missing on the front page)

**Pull request merged**
