### PR TITLE
Update install_mapserver.sh

### PR DESCRIPTION
**Pull request by sdlime**
Changed the script to point to demo updated for MapServer 7.0. See ticket at https://trac.osgeo.org/osgeo/ticket/1586.

### CODE REVIEW

**Comment by sdlime** [comment]
The new version of the demo zip file should be in place shortly. --Steve

**Comment by kalxas** [comment]
Thanks @sdlime 
The next nightly build, based on your commit will be ready in a few hours.

**Comment by tbonfort** [comment]
I'm not able to upload the archive yet, waiting on https://trac.osgeo.org/osgeo/ticket/1596

**Comment by kalxas** [comment]
@tbonfort what is the source file? I think I can upload it.

**Comment by kalxas** [comment]
I have uploaded https://github.com/mapserver/mapserver-demo/archive/master.zip to http://download.osgeo.org/livedvd/data/mapserver/mapserver-itasca-ms70.zip

Is that ok?

**Comment by kalxas** [comment]
Minor update here:
https://github.com/kalxas/OSGeoLive/commit/3eb58394b44398a14e4a09e3eaf804c11f51da18

**Pull request merged**
