### PR TITLE
Update demo for rasdaman

### PR DESCRIPTION
**Pull request by misev**
The existing demo was very outdated and had multiple issues. This updates it and fixes the problems.

### CODE REVIEW

**Comment by kalxas** [comment]
http://aiolos.survey.ntua.gr/gisvm/dev/osgeolive-nightly-build155-amd64-0f5cc3a-PR210.iso

http://aiolos.survey.ntua.gr/gisvm/dev/osgeolive-nightly-build155-amd64-0f5cc3a-PR210-log.tar.gz

System fails to boot on the live session.

**Comment by kalxas** [comment]
@misev is it possible that the rasdaman user was not properly patched in the new deb build?

**Comment by misev** [comment]
Indeed, it seems to have failed to do the user recreate hack:
```
Replacing regular user 'rasdaman' with a system user...
userdel: user rasdaman is currently used by process 28303
Failed removing rasdaman user.
```
I'll fix it, sorry about this.

**Comment by misev** [comment]
I will close this and make a pull request from scratch.

**Pull request closed without merging**
