### PR TITLE
Adding nbextension 

### PR DESCRIPTION
**Pull request by epifanio**
Added a sript to add notebook extension. For now only cesiumwidget ported. Tested on local build.

### CODE REVIEW

**Comment by kalxas** [comment]
There are several issues in this PR:
1. It will not work for 32 bit builds
2. There is no need for a separate installer
3. The deb files will be copied to jupyter ppa if they are tested and work.
4. Cesium widget can be packaged too

**Comment by kalxas** [comment]
I also object to this account here, it will confuse people that will try to find our source code:
https://github.com/OSGeo-live

**Comment by epifanio** [comment]
last changes should fix point 1
point 2:  the code in ```install_nbextension.sh``` has just one extension, but it is going to grow and get mote complex for next release. I prefer to have the extension separated from the main installer
point 3:  I tested adn they works, if you can upload them on the ppa i'll update the pr according to it
point 4:  i'm hacking the installer to avoid a copy of the cesium js code. this means that the resulting package of cesiumwidget will not work if cesium is not installed already (of course this can be solved adding a cesium package as dependency)

**Comment by epifanio** [comment]
in https://github.com/OSGeo-live there is the binder code I used to try to demo the notebooks developed during GSOC, and the hope was to receive PR to make better notebooks and add new one ... no contribution so far. Too unstable and uses anaconda python .. to Have it under OSGeo.

**Comment by kalxas** [comment]
point 1: ok, will clean up after merge
point 2: ok
point 3: the packages are already in the ppa, please update
point 4: ok for now.

**Comment by epifanio** [comment]
I cleaned the  install_nbextension.sh, it should install from main PPA

**Comment by kalxas** [comment]
Merged

**Pull request closed without merging**
