### PR TITLE
ossim-doc

### PR DESCRIPTION
**Pull request by epifanio**
added ossim pdf doc

### CODE REVIEW

**Comment by kalxas** [comment]
this will cost 10 MB

**Comment by epifanio** [comment]
I see, what if we replace:  OSSIMGeoCell__User_Manual__1.8.18-1.pdf (1.6 mb) 
with  ossim_users_guide.pdf  6.8 mb (which is much more complete) ? 
this way the update will cost 4.8mb.

**Comment by kalxas** [comment]
ok, and we can add those pdf urls in the docs, so people can easily find them online.

**Comment by epifanio** [comment]
in the quickstarter we have a link to:  http://download.osgeo.org/ossim/tutorials/pdfs/  i'll upload the geocell and ossimplanet pdf ther.

**Comment by kalxas** [comment]
Thanks.

**Comment by epifanio** [comment]
the quick starter now points to http://download.osgeo.org/ossim/docs/pdfs/ which contains newer pdfs

**Pull request merged**
