### PR TITLE
Update qfield to 3.1.9

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by kalxas** [comment]
Thank you @m-kuhn for the update.
We will handle it when we start working on version 17.0

**Comment by m-kuhn** [comment]
@kalxas no problem, I was wondering if there are 16.x minor versions planned and otherwise if there's a start date for 17.0 (probably a new version will be active then)

**Comment by kalxas** [comment]
No minor versions planned right now, unless critical bugs pile up...
The new version planning will probably start in April, just before the new Ubuntu LTS release

**Comment by m-kuhn** [comment]
@kalxas we can follow up with a newer version.

Any chance to get this onto the system so it can be used in workshops?

**Pull request merged**
