### PR TITLE
Replace old qgis-mapserver with QGIS Web Client 2

### PR DESCRIPTION
**Pull request by HusseinKabbout**
This PR replaces the old QGIS Web Client with the latest version of the QGIS Web Client 2. The new Map Viewer would look like this:
image

### CODE REVIEW

**Comment by HusseinKabbout** [comment]
This PR replaces the old QGIS Web Client with the latest version of the QGIS Web Client 2. The new Map Viewer would look like this:
image

**Comment by HusseinKabbout** [comment]
I removed the commit and rebased this PR.

**Comment by kalxas** [comment]
Thank you for your contribution.
I will merge once we start builds for the next version (waiting for the final LTS of Ubuntu 20.04)

**Comment by HusseinKabbout** [comment]
@kalxas Any updates on this PR?

**Comment by kalxas** [comment]
Thanks, we will review the PR once we have a working build solution for the iso (work in progress)

**Comment by kalxas** [comment]
Hi @HusseinKabbout @pka 
I am wondering if the source code included in this PR is maintained on a separate git repository somewhere. In that case we could just pull the code during build instead of keeping a copy in this repository.

**Comment by kalxas** [comment]
btw I am now in the process to merge, since we are moving ahead with builds

**Comment by HusseinKabbout** [comment]
The code for the QWC2 core components can be found (here)[https://github.com/qgis/qwc2].

But for this PR I used the (qwc-2demo-app)[https://github.com/qgis/qwc2-demo-app] as my base QWC2 build and then configured it accordingly.

> we could just pull the code during build instead of keeping a copy in this repository

This makes sense, but I would need to make some tests and also remove everything from this PR that can be pulled from the other repository. I will have a look at it tomorow or during the weekend.

> btw I am now in the process to merge, since we are moving ahead with builds

Until when do I have time to make the changes?

**Comment by kalxas** [comment]
We have not yet hit alpha, so there is enough time to fix.

Thanks for the feedback.

**Comment by pka** [comment]
The usual process for a qwc2 application is cloning the [qwc2-demo-app](https://github.com/qgis/qwc2-demo-app/) repo and add custom config and code to it. That's the content of this PR. But since there's no code addition in this case, it should be possible to download a build from https://github.com/qgis/qwc2-demo-app/releases and add the configuration only.

**Comment by pka** [comment]
@HusseinKabbout ?

**Comment by kalxas** [comment]
amazing, I was about to ask when you posted!

**Comment by HusseinKabbout** [comment]
kalxas  After you said that we still have time, I put it on low prio on my todo list and got busy with work/school stuff. I am sorry for the delay. I will have a look at it tomorow.

**Comment by HusseinKabbout** [comment]
@kalxas I have removed all files that were not needed. The only files I kept were the config files for the viewer. (`config.json` and `themes.json`)

As @pka said, you can download a build from https://github.com/qgis/qwc2-demo-app/releases and just replace those two config files.

**Comment by pka** [comment]
@HusseinKabbout could you include the required changes in the install script (https://github.com/OSGeo/OSGeoLive/blob/master/bin/install_qgis_server.sh#L61) in the PR?

**Comment by HusseinKabbout** [comment]
@pka I have updated the install script. Is there anything else that should be updated?

**Comment by kalxas** [comment]
Looks good, thanks, I can merge and test the next nightly build

**Comment by kalxas** [comment]
@HusseinKabbout @pka unfortunately this does not work in current iso.
Can you please check logs of alpha2 and fix?
http://aiolos.survey.ntua.gr/gisvm/14.0/osgeolive-14.0alpha2-amd64-log.tar.gz

**Pull request merged**
