### PR TITLE
Notebooktest

### PR DESCRIPTION
**Pull request by darkblue-b**
this is a working branch, subject to change; built cleanly against master branch;  adds R kernel via CRAN and IRkernel snapshot

### CODE REVIEW

**Comment by kalxas** [comment]
scheduled for next nightly - later today

**Comment by Bakaniko** [comment]
Tested yesterday

R works fine in Jupyter notebooks with the IRKernel. I think as it is installed we can skip on the Rstudio interface and keep it light weighted.

*sf* packages links directly to system librairies like GEOS or GDAL (lighter for us, old sp package embedded us)

r_geos_gdal

Plot is limited for mapping. I suggest to had [ggplot2 3.0 for better mapping compatibilites - please read the *sf* part](https://www.tidyverse.org/articles/2018/05/ggplot2-2-3-0/)
r_notebook

**Comment by Bakaniko** [comment]
List of installed package as today:
[R_installed_packages_20180725.csv.zip](https://github.com/OSGeo/OSGeoLive/files/2228758/R_installed_packages_20180725.csv.zip)

**Comment by kalxas** [comment]
thanks!

**Comment by kalxas** [comment]
shall we just close this one?

**Pull request closed without merging**
