### PR TITLE
alt desktop boboli

### PR DESCRIPTION
**Pull request by darkblue-b**
desktop using boboli gardens image

### CODE REVIEW

**Comment by lucadelu** [comment]
I prefer this one instead of #332

**Comment by edeso** [comment]
the picture is still translucent by a margin. why is that?

**Comment by edeso** [comment]
@darkblue-b also can you maybe point me to the original image? looks like it contains some artifacts from downscaling. see attached
scaling

**Comment by edeso** [comment]
tried to send some comment to the list but failed due to the 60kb attachment limit. what i wrote was

i tried both. some desktop symbol texts become unreadable. should we add a gradient from the left that darkens it much more or ... ? 
bobo
fire

as compared to
osgeo14

**Pull request closed without merging**
