### PR TITLE
update to uDig 2.2.0.RC1

### PR DESCRIPTION
**Pull request by fgdrf**
Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>

### CODE REVIEW

**Comment by fgdrf** [comment]
> 
> 
> hi Frank - please update when the uDig RC1 goes to RELEASE; thank you and be well --dbb

Hmm, its an release but we cannot name it that way (for IP Review reasons of Eclipse Foundation). Would be great to get it into OSGeo Live distribution

**Comment by kalxas** [comment]
ok thanks

**Comment by kalxas** [comment]
@fgdrf the pull request has been merged but uDig is not working as expected in the nightly build.
Can you please download the latest iso from http://aiolos.survey.ntua.gr/gisvm/dev/ or http://download.osgeo.org/livedvd/nightly/ and test?

**Comment by fgdrf** [comment]
Going to have a look at...

When is the release planned for?

—
Frank

Angelos Tzotsos <notifications@github.com> schrieb am So. 4. Okt. 2020 um
17:46:

**Comment by kalxas** [comment]
I am working for an alpha release so the final release should be a couple of months away...

**Comment by kalxas** [comment]
@fgdrf I am adding more info in a ticket:
https://trac.osgeo.org/osgeolive/ticket/2281

**Comment by kalxas** [comment]
Please note that we are trying to reach beta stage soon, release targeted early 2021.

**Pull request merged**
