### PR TITLE
Update GeoMoose to 2.9.2.

### PR DESCRIPTION
**Pull request by klassenjs**
GeoMoose 2.9.2 is the latest bugfix release of the GeoMoose 2.9 series.

### CODE REVIEW

**Comment by klassenjs** [comment]
Looking now.

**Comment by klassenjs** [comment]
It should be fixed now.  The download tarball didn't get built correctly (looks like the build process got run twice at the same time somehow).

**Comment by kalxas** [comment]
Thank you, I will test again

**Comment by kalxas** [comment]
Works fine now, thanks

**Pull request merged**
