### PR TITLE
Updating eoxserver installation script for version 0.4.0

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by kalxas** [comment]
@constantinius I am getting a configuration error when I open the web client.
Autotest download failed. 

--2015-07-02 19:09:43--  https://github.com/EOxServer/autotest/archive/release-0.4beta3.tar.gz
Resolving github.com (github.com)... 192.30.252.131
Connecting to github.com (github.com)|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/EOxServer/autotest/tar.gz/release-0.4beta3 [following]
--2015-07-02 19:09:43--  https://codeload.github.com/EOxServer/autotest/tar.gz/release-0.4beta3
Resolving codeload.github.com (codeload.github.com)... 192.30.252.146
Connecting to codeload.github.com (codeload.github.com)|192.30.252.146|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-02 19:09:44 ERROR 404: Not Found.

**Comment by constantinius** [comment]
@kalxas: I forgot to make an autotest release as well, the link above works now (here is the release landing page: https://github.com/EOxServer/autotest/releases/tag/release-0.4beta3)

**Comment by kalxas** [comment]
@constantinius thanks, building a new iso right now

**Comment by kalxas** [comment]
Everything works fine now in http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-build69-amd64-eeadcf2-log.tar.gz

**Pull request merged**
