### PR TITLE
[osm data] adding Florence, Italy OSM data

### PR DESCRIPTION
**Pull request by cvvergara**
Data Includes the workshop and venue location.
Approximately:  3964367b when compressed

### CODE REVIEW

**Comment by cvvergara** [comment]
checking, the workshop venue is not included in this dataset BBOX, will check it over

**Comment by kalxas** [comment]
ok, I will wait for an update

**Comment by darkblue-b** [comment]
the OSM data is cached, for the build machinery - OSM data files are with the static build assets ..   `download osgeo  livedvd/data/osm/FIRENZE_IT/`  ..

**Comment by cvvergara** [comment]
ah, I see there was a push.
I will close, I think the contents are ok now

**Pull request closed without merging**
