### PR TITLE
Update install_ipython.sh

### PR DESCRIPTION
**Pull request by epifanio**
Replaced ipython installation with custom deb packages and added new jupyter notebook

### CODE REVIEW

**Comment by kalxas** [comment]
merged in https://github.com/OSGeo/OSGeoLive/commit/196cdfe9d191788618b0b4795dd9b3f930774e99

**Comment by epifanio** [comment]
I reopened the PR, i had to fix small bug in the script. Now the app works fine but i still have to finish the script. I'm missing icons, docs and desktop launchers. In the meantime is worth to test the build

**Comment by kalxas** [comment]
I had the impression that this update would go to GSoC branch.
Are you proposing that jupiter should be included now?

**Comment by epifanio** [comment]
Yes, it is worth a try.
I checked the IPython repository for newer version, they still have 2.3 no pkg available for 3.2 for ubuntu 14.04. 
This update install  new version of Ipython and add Jupyter. 
I think this set of updates will make the live better, my only concern is about space.
We need to check the final space on disc because it includes some more packages 
(this installer adds libraries used by other installers so in its total size there are "mb" shared with other projects)

**Comment by epifanio** [comment]
i fixed the launchers and icon stuff, it should work properly now.

**Comment by kalxas** [comment]
@epifanio I only see one commit in this PR which conflicts with master because it cannot be applied without the previous jupiter commit. 
I do not see the launcher fix you mention, neither commit https://github.com/OSGeo/OSGeoLive/commit/eda1a8b4873ebba1a02d843ae0177bfe4b990c30 applies to master right now.
Please fix or close this PR.

**Comment by kalxas** [comment]
I will build a nightly from GSoC branch and let you know the result.

**Comment by kalxas** [comment]
ok, the confusion was between GSoC and GSoC2015 branches...

**Comment by kalxas** [comment]
Logs:
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-build92-amd64-ca3a83b-log.tar.gz

**Comment by epifanio** [comment]
I found an error in  a .deb (a dependencde was listed as "python2-numpy", while it should be "python-numpy") i fixed it and a fixed an other issue with the port (i tested only 32bit before, this are the first test with 64bit) I'll try a fresh run of the script and report here.

**Comment by epifanio** [comment]
I tested both archs, it should be ok now. 
I wasn't able to download the log.

**Comment by epifanio** [comment]
ok seems i saw waht you mean about gsoc and gsoc2015 branches ... that's very confusing. I'll close this and make a new one to gsoc branch. sorry .. still learning git :(

**Comment by epifanio** [comment]
link to the new [PR25](https://github.com/OSGeo/OSGeoLive/pull/25)

**Pull request closed without merging**
