### PR TITLE
Update actinia versions

### PR DESCRIPTION
**Pull request by mmacata**
This PR
- updates versions of actinia plugins
- removes separate installation of actinia-api as it is automatically installed with `pip install actinia-core`. This way, no version mismatch can occur.

~~(Draft as not tested yet)~~

### CODE REVIEW

**Comment by neteler** [comment]
I have tested it with the related Ubuntu docker image and run into a problem (solution below):

```bash
podman run -it --rm ubuntu:22.04
Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/ubuntu:22.04...
Getting image source signatures
Copying blob 3713021b0277 done   | 
...

apt-get update
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
...

apt-get install wget -y
...

wget https://raw.githubusercontent.com/OSGeo/OSGeoLive/92363d3896247af81308a563fb487ce28678d91c/bin/install_actinia.sh
sh -x install_actinia.sh
+ basename install_actinia.sh
+ ./diskspace_probe.sh install_actinia.sh begin
...
Installing collected packages: uWSGI, snowballstemmer, ply, wheel, tzdata, tqdm, tomli, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, snuggs, setuptools, pyogrio, Pygments, psutil, msgpack, imagesize, html2text, geomet, geojson, docutils, cligj, click-plugins, babel, attrs, alabaster, affine, Sphinx, sentinelsat, rasterio, pandas, matplotlib, fluent-logger, geopandas, google-cloud-bigquery, actinia-api, actinia-core
  Running setup.py install for uWSGI ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for uWSGI did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      /usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'descriptions'
        warnings.warn(msg)
      running install
      /opt/actinia_core/venv-actinia/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      using profile: buildconf/default.ini
      detected include path: ['/usr/include', '/usr/local/include']
      Traceback (most recent call last):
        File "/tmp/pip-install-88l9_iio/uwsgi_a9ae6231144c4fdbb0b8e31df5640fbb/uwsgiconfig.py", line 752, in __init__
          gcc_version_components = gcc_version.split('.')
      AttributeError: 'NoneType' object has no attribute 'split'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-88l9_iio/uwsgi_a9ae6231144c4fdbb0b8e31df5640fbb/setup.py", line 117, in <module>
          setup(
        File "/opt/actinia_core/venv-actinia/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-88l9_iio/uwsgi_a9ae6231144c4fdbb0b8e31df5640fbb/setup.py", line 77, in run
          conf = uc.uConf(get_profile())
        File "/tmp/pip-install-88l9_iio/uwsgi_a9ae6231144c4fdbb0b8e31df5640fbb/uwsgiconfig.py", line 760, in __init__
          raise Exception("you need a C compiler to build uWSGI")
      Exception: you need a C compiler to build uWSGI
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> uWSGI

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
+ /opt/actinia_core/venv-actinia/bin/python3 -m pip install https://github.com/actinia-org/actinia-statistic-plugin/releases/download/0.2.2/actinia_statistic_plugin-0.2.2-py2.py3-none-any.whl
Collecting actinia-statistic-plugin==0.2.2
  Downloading https://github.com/actinia-org/actinia-statistic-plugin/releases/download/0.2.2/actinia_statistic_plugin-0.2.2-py2.py3-none-any.whl (34 kB)
Installing collected packages: actinia-statistic-plugin
Successfully installed actinia-statistic-plugin-0.2.2
+ /opt/actinia_core/venv-actinia/bin/python3 -m pip install https://github.com/actinia-org/actinia-satellite-plugin/releases/download/0.1.2/actinia_satellite_plugin-0.1.2-py2.py3-none-any.whl
Collecting actinia-satellite-plugin==0.1.2
  Downloading https://github.com/actinia-org/actinia-satellite-plugin/releases/download/0.1.2/actinia_satellite_plugin-0.1.2-py2.py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.2/47.2 KB 1.9 MB/s eta 0:00:00
Installing collected packages: actinia-satellite-plugin
Successfully installed actinia-satellite-plugin-0.1.2
+ /opt/actinia_core/venv-actinia/bin/python3 -m pip install https://github.com/actinia-org/actinia-module-plugin/releases/download/2.6.0/actinia_module_plugin.wsgi-2.6.0-py2.py3-none-any.whl
Collecting actinia-module-plugin.wsgi==2.6.0
  ERROR: HTTP error 404 while getting https://github.com/actinia-org/actinia-module-plugin/releases/download/2.6.0/actinia_module_plugin.wsgi-2.6.0-py2.py3-none-any.whl
ERROR: Could not install requirement actinia-module-plugin.wsgi==2.6.0 from https://github.com/actinia-org/actinia-module-plugin/releases/download/2.6.0/actinia_module_plugin.wsgi-2.6.0-py2.py3-none-any.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/actinia-org/actinia-module-plugin/releases/download/2.6.0/actinia_module_plugin.wsgi-2.6.0-py2.py3-none-any.whl for URL https://github.com/actinia-org/actinia-module-plugin/releases/download/2.6.0/actinia_module_plugin.wsgi-2.6.0-py2.py3-none-any.whl
+ cp //../app-conf/actinia/actinia.cfg /etc/actinia//actinia.cfg
cp: cannot stat '//../app-conf/actinia/actinia.cfg': No such file or directory
+ ln -s /home/user/grassdata/nc_basic_spm_grass7 /opt/actinia_core/grassdb
+ grass --text -e -c EPSG:25832 /opt/actinia_core/grassdb/utm32n
install_actinia.sh: 103: grass: not found
+ grass --text -e -c EPSG:4326 /opt/actinia_core/grassdb/latlong
install_actinia.sh: 104: grass: not found
+ mkdir -p /usr/local/bin
+ cat
+ chmod 755 /usr/local/bin/actinia_start.sh
+ chmod -R 777 /opt/actinia_core
+ echo Downloading actinia logo ...
Downloading actinia logo ...
+ wget -c --progress=dot:mega -O /usr/local/share/icons/actinia.png https://github.com/actinia-org/actinia-core/raw/main/docs/docs/actinia_logo.png
/usr/local/share/icons/actinia.png: No such file or directory
+ cat
+ cp -a /usr/share/applications/actinia-start.desktop /home/user/Desktop/
cp: cannot create regular file '/home/user/Desktop/': No such file or directory
+ chown -R user:user /home/user/Desktop/actinia-start.desktop
chown: invalid user: 'user:user'
+ basename install_actinia.sh
+ //diskspace_probe.sh install_actinia.sh end
```

The `Exception: you need a C compiler to build uWSGI` can be addressed with:

```bash
apt-get install build-essential python3-dev -y
```

**Comment by neteler** [comment]
Some more issues:

```bash
...
Collecting actinia-module-plugin.wsgi==2.6.0
  ERROR: HTTP error 404 while getting https://github.com/actinia-org/actinia-module-plugin/releases/download/2.6.0/actinia_module_plugin.wsgi-2.6.0-py2.py3-none-any.whl
ERROR: Could not install requirement actinia-module-plugin.wsgi==2.6.0 from https://github.com/actinia-org/actinia-module-plugin/releases/download/2.6.0/actinia_module_plugin.wsgi-2.6.0-py2.py3-none-any.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/actinia-org/actinia-module-plugin/releases/download/2.6.0/actinia_module_plugin.wsgi-2.6.0-py2.py3-none-any.whl for URL https://github.com/actinia-org/actinia-module-plugin/releases/download/2.6.0/actinia_module_plugin.wsgi-2.6.0-py2.py3-none-any.whl
```

The correct URL would be:
https://github.com/actinia-org/actinia-module-plugin/releases/download/2.6.0/actinia_module_plugin-2.6.0-py3-none-any.whl

**Comment by mmacata** [comment]
@neteler I added your suggestions. Can you test again please ?

**Comment by neteler** [comment]
Much better! The remaining issues (probably due to my simple `podman` test or wrong docker image?):

```
[...]
Successfully installed actinia-module-plugin-2.6.0
+ cp //../app-conf/actinia/actinia.cfg /etc/actinia//actinia.cfg
cp: cannot stat '//../app-conf/actinia/actinia.cfg': No such file or directory
+ ln -s /home/user/grassdata/nc_basic_spm_grass7 /opt/actinia_core/grassdb
ln: failed to create symbolic link '/opt/actinia_core/grassdb/nc_basic_spm_grass7': File exists
+ grass --text -e -c EPSG:25832 /opt/actinia_core/grassdb/utm32n
install_actinia.sh: 103: grass: not found
+ grass --text -e -c EPSG:4326 /opt/actinia_core/grassdb/latlong
install_actinia.sh: 104: grass: not found
+ mkdir -p /usr/local/bin
+ cat
+ chmod 755 /usr/local/bin/actinia_start.sh
+ chmod -R 777 /opt/actinia_core
+ echo Downloading actinia logo ...
Downloading actinia logo ...
+ wget -c --progress=dot:mega -O /usr/local/share/icons/actinia.png https://github.com/actinia-org/actinia-core/raw/main/docs/docs/actinia_logo.png
/usr/local/share/icons/actinia.png: No such file or directory
+ cat
+ cp -a /usr/share/applications/actinia-start.desktop /home/user/Desktop/
cp: cannot create regular file '/home/user/Desktop/': No such file or directory
+ chown -R user:user /home/user/Desktop/actinia-start.desktop
chown: invalid user: 'user:user'
+ basename install_actinia.sh
+ //diskspace_probe.sh install_actinia.sh end
install_actinia.sh: 161: //diskspace_probe.sh: not found
```

**Comment by mmacata** [comment]
Does this error `install_actinia.sh: 161: //diskspace_probe.sh: not found` appear also at the beginning of the output? In the `install_actinia.sh` it looks like it is called twice https://github.com/OSGeo/OSGeoLive/blob/master/bin/install_actinia.sh#L43

Either way it looks pretty much like a setup error to me. I don't know much about it, but I doubt, that above changes are responsible for this error, so I think it is ok?

**Comment by neteler** [comment]
Yes, same error at the beginning:

```
root@98299ef4c7b6:/# sh -x install_actinia.sh
+ basename install_actinia.sh
+ ./diskspace_probe.sh install_actinia.sh begin
install_actinia.sh: 43: ./diskspace_probe.sh: not found
```

Not an issue for this test, indeed.

But this is also a problem:

`install_actinia.sh: 103: grass: not found`

**Comment by mmacata** [comment]
Maybe not as there is the separate [install_grass.sh](https://github.com/OSGeo/OSGeoLive/blob/master/bin/install_grass.sh) !?

**Comment by neteler** [comment]
You are right. I needed to mount this repo into the docker container.

Doing so, I managed to launch actinia, but the `xmltodict` module still seems to be missing:

```
actinia_start.sh 
13226:C 01 Aug 2024 10:51:32.910 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
13226:C 01 Aug 2024 10:51:32.910 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=13226, just started
13226:C 01 Aug 2024 10:51:32.910 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 6.0.16 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 13226
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

13226:M 01 Aug 2024 10:51:32.911 # Server initialized
13226:M 01 Aug 2024 10:51:32.911 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
13226:M 01 Aug 2024 10:51:32.912 * Ready to accept connections
PONG
Created user <actinia-gdi> in group <superadmin>
user_id: actinia-gdi
user_role: superadmin
user_group: superadmin
permissions: {'accessible_datasets': {'nc_spm_08': ['PERMANENT', 'user1', 'landsat'], 'ECAD': ['PERMANENT'], 'latlong_wgs84': ['PERMANENT']}, 'accessible_modules': ['d.legend', 'd.rast', 'd.rast.multi', 'd.vect', 'exporter', 'g.findfile', 'g.gisenv', 'g.list', 'g.mapset', 'g.proj', 'g.region', 'g.remove', 'g.rename', 'g.version', 'i.atcorr', 'i.cluster', 'i.colors.enhance', 'i.gensig', 'i.group', 'i.landsat.toar', 'i.maxlik', 'i.pansharpen', 'i.segment', 'i.tasscap', 'i.vi', 'importer', 'r.blend', 'r.buffer', 'r.buffer.lowmem', 
[...]
'v.rast.stats', 'v.select', 'v.what.rast', 'v.what.strds'], 'cell_limit': 100000000000, 'process_num_limit': 1000, 'process_time_limit': 31536000}
[2024-08-01 10:51:34 +0200] [13234] [INFO] Starting gunicorn 22.0.0
[2024-08-01 10:51:34 +0200] [13234] [INFO] Listening at: http://0.0.0.0:8088 (13234)
[2024-08-01 10:51:34 +0200] [13234] [INFO] Using worker: sync
[2024-08-01 10:51:34 +0200] [13235] [INFO] Booting worker with pid: 13235
Could not find any config file, using default values.
{'message': "No module named 'xmltodict'",
 'traceback': "['  File "
              '"/opt/actinia_core/venv-actinia/lib/python3.10/site-packages/actinia_core/endpoints.py", '
              "line 368, in create_endpoints\\n    check_import_plugins()\\n', "
              "'  File "
              '"/opt/actinia_core/venv-actinia/lib/python3.10/site-packages/actinia_core/endpoints.py", '
              'line 362, in check_import_plugins\\n    '
              'exec(import_run_str)\\n\', \'  File "<string>", line 1, in '
              "<module>\\n', '  File "
              '"/opt/actinia_core/venv-actinia/lib/python3.10/site-packages/actinia_module_plugin/endpoints.py", '
              'line 32, in <module>\\n    from '
              "actinia_module_plugin.api.modules.grass import ListModules\\n', "
              "'  File "
              '"/opt/actinia_core/venv-actinia/lib/python3.10/site-packages/actinia_module_plugin/api/modules/grass.py", '
              'line 37, in <module>\\n    from '
              'actinia_module_plugin.core.modules.grass import '
              "createModuleList\\n', '  File "
              '"/opt/actinia_core/venv-actinia/lib/python3.10/site-packages/actinia_module_plugin/core/modules/grass.py", '
              'line 35, in <module>\\n    from '
              'actinia_module_plugin.core.modules.parser import '
              "ParseInterfaceDescription\\n', '  File "
              '"/opt/actinia_core/venv-actinia/lib/python3.10/site-packages/actinia_module_plugin/core/modules/parser.py", '
              "line 30, in <module>\\n    import xmltodict\\n']",
 'type': "<class 'ModuleNotFoundError'>"}

```

**Comment by neteler** [comment]
(I have updated `install_grass.sh` here: #392)

**Comment by mmacata** [comment]
I updated the actinia-module-plugin to include xmltodict as a requirement. Could you please test one more time?

**Review by neteler — APPROVED** [review]
I have tested it now in docker, looks ok.

Additionally, I tried to test using the OSGeoLive nightly ISO files (http://download.osgeo.org/livedvd/nightly/) but did not manage to boot that.

So, I think that the changes are fine.

**Comment by mmacata** [comment]
Thanks, so from my point of view this is able to be merged as well.
(I have no merge rights)

**Comment by kalxas** [comment]
Thank you, I will merge once this is tested in a nightly build.

**Review by kalxas — APPROVED** [review]

**Pull request merged**
