### PR TITLE
Add qfield to icons and menus

### PR DESCRIPTION
**Pull request by m-kuhn**
https://github.com/OSGeo/OSGeoLive-doc/pull/808#discussion_r1188627792

### CODE REVIEW

**Comment by sanak** [comment]
@m-kuhn  
I built ISO from my forked branch (https://github.com/sanak/OSGeoLive/tree/install-qfield2), and it seems to work as expected.
osgeolive-qfield-menu-order

I upload the ISO image to my Google Drive, so just for your information.
https://drive.google.com/file/d/1rx0MYwqm7qVAlmNVehnUykO1Ku_eTTI0/view?usp=share_link
(The build command was `sudo ./build_chroot.sh amd64 nightly install-qfield2 sanak 2>&1 | tee /var/log/osgeolive/chroot-build.log`)

**Comment by m-kuhn** [comment]
thank you very much.
Can I treat this as approval for this pull request?

**Comment by sanak** [comment]
> Can I treat this as approval for this pull request?

Well, I am just one of the contributors, so the maintainers approval will be necessary, I think.

**Review by kalxas — APPROVED** [review]

**Comment by kalxas** [comment]
Thank you!

**Pull request merged**
