### PR TITLE
GeoNetwork / Update to version 3.0.0.

### PR DESCRIPTION
**Pull request by fxprunayre**
This PR updates GeoNetwork from version 2.10.4 to 3.0.0.

See https://github.com/geonetwork/core-geonetwork/issues/895

The GN3 documentation is being updated, we'll also update the OSGeo quickstart (https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/quickstart/geonetwork_quickstart.rst) as part of this work.

### CODE REVIEW

**Comment by kalxas** [comment]
@fxprunayre thanks for the upgrade, can you please specify how much memory on your VM for comparison reasons?

**Comment by fxprunayre** [comment]
My first test was with 512m RAM which is a bit to low (for system+app). I set up the memory to be between 512-1024m when the Java app starts which should be fine for version 3.

**Comment by kalxas** [comment]
Thanks, I am in the process of starting new builds so I will merge within this week.

**Comment by kalxas** [comment]
We are still reviewing stuff, so this merge will be a bit delayed.

**Comment by kalxas** [comment]
I am getting this error on nightly build when starting geonetwork 3:

user@osgeolive:/usr/local/lib/geonetwork/bin$ ./startup.sh 
rm: cannot remove ‘logs/*request.log*’: No such file or directory
mv: cannot stat ‘logs/geonetwork.log.*’: No such file or directory
mv: cannot stat ‘logs/geoserver.log.*’: No such file or directory

(process:3928): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

**Comment by kalxas** [comment]
And this is the build to test:
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-build43-amd64-197bd38.iso

**Comment by kalxas** [comment]
Actually I just tested previous installer and I get this error again.
It seems that 64bit architecture is causing this issue and not the actual commit.

**Comment by kalxas** [comment]
Java home was not set properly in 64 environment, this commit is now merged

**Comment by fxprunayre** [comment]
> rm: cannot remove ‘logs/request.log’: No such file or directory
> mv: cannot stat ‘logs/geonetwork.log.’: No such file or directory
> mv: cannot stat ‘logs/geoserver.log.’: No such file or directory

Those are only startup warning when the app first start and no log file were available. I'll test the new build. Thanks

**Comment by kalxas** [comment]
Does this new version have an embeded geoserver?

**Comment by fxprunayre** [comment]
It does, but it's not installed on the OSGeo Live as it's not needed for default usage.

**Comment by kalxas** [comment]
Thanks for the clarification.

**Pull request merged**
