### PR TITLE
Geoext Install

### PR DESCRIPTION
**Pull request by geographika**
This pull request installs the GeoExt project and its dependencies - OL 4.6.5 and ExtJS 6.2 (GPL version)

Used install_openlayers.sh as a template

GeoExt requires OpenLayers 4.6.5 - this is the current OL release on OSGeoLive - could symlink to this version but if OL is updated independently the GeoExt demo will be broken.

### CODE REVIEW

**Comment by kalxas** [comment]
Thank you @geographika 
I will include this script in the next nightly build so we can test.

**Comment by geographika** [comment]
I'm unsure if files (the demo rather than docs) can be placed directly in /var/www/html/geoext or if this needs to be symlinked from /usr/local/share/geoext or similar. 
The quickstart assumes a user can create an HTML file in /var/www/html/geoext so will check permissions. 

I tested the script in parts on a OSGeoLive VM, but not yet gone through the whole OSGeoLive build process from scratch.

**Comment by geographika** [comment]
I tried the ISO at http://aiolos.survey.ntua.gr/gisvm/dev/osgeolive-nightly-build55-amd64-37a470f-PR258.iso - no GeoExt unfortunately. 

I had a quick review of the logs:

main_log_errors.log

- mv: cannot stat 'geoext.desktop': No such file or directory

chroot-build.log

- /tmp/inchroot.sh: 203: /tmp/inchroot.sh: ./install_geoext.sh: Permission denied

I'm guessing I missed setting a permission somewhere - will investigate further later, but if anything is obvious to others please let me know.

**Comment by kalxas** [comment]
I have fixed this on my PR258 branch and trying a new build now

**Comment by kalxas** [comment]
oops, it should be PR257 branch :)

**Comment by kalxas** [comment]
New iso available.
The installation has worked this time and I am about to make some minor changes to the installer and merge.

**Comment by kalxas** [comment]
Merged

**Pull request closed without merging**
