### PR TITLE
Updated the install_gvsig to gvSIG desktop 2.4.0

### PR DESCRIPTION
**Pull request by jjdelcerro**

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @jjdelcerro 
Does this new version work with Java 8?
What is the footprint on disk space?

**Comment by jjdelcerro** [comment]
Hi Angelos,
Yes, it works with java 8.
The disk space used is about 450Mb.

**Comment by kalxas** [comment]
Does the new package provided include a jre?
I ask because you had provided a "no-jre" package in the past.

**Comment by kalxas** [comment]
@jjdelcerro since you are a first time committer, can you please accept the license agreement as described here:
https://trac.osgeo.org/osgeolive/wiki/Source_code#Commitaccess

**Comment by jjdelcerro** [comment]
Hi Angelos,
it does not include the jre.

**Comment by jjdelcerro** [comment]
I subscribed to the OSGeo-Live list
and I have sent a message accepting that my contributions are compatible with the OSGeo license.

**Comment by kalxas** [comment]
thank you

**Comment by kalxas** [comment]
We have created a test build with this PR included, the result is here:
http://aiolos.survey.ntua.gr/gisvm/dev/osgeolive-nightly-build128-amd64-31ebe1b-PR206.iso
http://aiolos.survey.ntua.gr/gisvm/dev/osgeolive-nightly-build128-amd64-31ebe1b-PR206-log.tar.gz

Comparison of disk size usage:
This is from 12.0alpha1, gvSIG at 197MB
disk_usage_plot1

and this is from latest build, gvSig at 445MB
disk_usage_plot

We are going to discuss this today in our weekly OSGeoLive meeting. This increase in disk size might lead to exclude other projects from the iso, and this would be a problem.

**Comment by kalxas** [comment]
There has not been a resolution of this issue yet, will discuss on the meeting tonight

**Comment by darkblue-b** [comment]
new dot-deb is available as   **gvsig-desktop_2.4.0-2850-2_amd64.deb**

**Comment by kalxas** [comment]
hi @jjdelcerro has there been a reduced gvsig deb so we can use it in this OSGeoLive release?

**Comment by kalxas** [comment]
Hi @jjdelcerro any update on this topic?
We are thinking about including projects with big disk footprint on the VM version only for our next release (not decided yet).
Is this something that would be ok for you?

**Comment by kalxas** [comment]
Merged manually in 3c6174d

**Pull request closed without merging**
