### PR TITLE
Create install_nbextension.sh

### PR DESCRIPTION
**Pull request by epifanio**
Add script to install notebook extensions

### CODE REVIEW

**Comment by epifanio** [comment]
Perhaps this script should be moved to ```app-conf/jupyter```, please don't merge, I'll continue to work on this PR.

**Comment by kalxas** [comment]
ok, will wait

**Comment by epifanio** [comment]
mistake .. i did a push and it went to master instead of a branch

**Comment by epifanio** [comment]
I added this file on the repo: https://github.com/OSGeo/OSGeoLive/blob/master/app-conf/jupyter/install_nbextension.sh

**Comment by kalxas** [comment]
reverted

**Comment by epifanio** [comment]
we can remove this pr, i applied the changes in https://github.com/OSGeo/OSGeoLive/pull/91

**Pull request closed without merging**
