### PR TITLE
updated sh script to version 3.0.7.3

### PR DESCRIPTION
**Pull request by astroidex**
* we have a new release 3.0.7.3
* updated sh and spreadsheet

### CODE REVIEW

**Comment by kalxas** [comment]
@astroidex after building the iso based on this PR I see a 54MB disk size increase (compressed!)
```
-rw-r--r-- 1 osgeo guests 4204789760 Aug  2 14:35 osgeolive-nightly-build163-amd64-f2ec780-master.iso
-rw-r--r-- 1 osgeo guests 4258267136 Aug  4 12:05 osgeolive-nightly-build164-amd64-46817dc-PR219.iso
```
Can it be that the change from `http://www.mapbender.org/builds/osgeolive` to `http://www.mapbender.org/builds/3.0.7.3` introduces more sample data in the disk?

**Comment by kalxas** [comment]
Thanks @astroidex 
Going to rebuild and confirm.

**Comment by kalxas** [comment]
After removing the docs, the disk is still 54MB larger.
```
-rw-r--r-- 1 osgeo guests 4204789760 Aug  2 14:35 osgeolive-nightly-build163-amd64-f2ec780-master.iso
-rw-r--r-- 1 osgeo guests 4258267136 Aug  4 23:13 osgeolive-nightly-build168-amd64-0200dfa-PR219.iso
```
I will investigate further before merging.

**Comment by kalxas** [comment]
Looking at the download server files, I see that previously installed version has a tar file of size 23M
`https://www.mapbender.org/builds/osgeolive/mapbender3-starter-3.0.7.0-RC2.tar.gz`
the new file is 93M
`https://www.mapbender.org/builds/mapbender3-starter-3.0.7.3.tar.gz`

**Comment by kalxas** [comment]
current master iso:
```
cd /var/www/html/mapbender
du -skh
103M
```

PR219 iso:
```
/var/www/html/mapbender
du -skh
184M
```

**Comment by astroidex** [comment]
I will have a look too and come back to you.

**Comment by kalxas** [comment]
Found the problem from the build logs:
```
rm: cannot remove '/var/www/html/web/docs/': No such file or directory
```

**Comment by kalxas** [comment]
merged in master

**Comment by astroidex** [comment]
Hi Angelos. Sure! Sorry. I should have tested it. Urg.

**Pull request closed without merging**
