### PR TITLE
Update GeoMoose to 2.9.0.

### PR DESCRIPTION
**Pull request by klassenjs**
GeoMoose 2.9.0 is the latest stable version and fixes many known issues with older versions.

### CODE REVIEW

**Comment by kalxas** [comment]
Hi @klassenjs 
I just merged this PR in my xenial branch.
Can you please confirm that GeoMoose will work with php-sqlite3 included in Ubuntu Xenial? PHP5 was removed in 16.04
https://github.com/kalxas/OSGeoLive/commit/049574cb6b462ffe5f12b2dd6c6685784c9215ad

**Comment by klassenjs** [comment]
I haven't been able to test because I can't get the VM to build locally.  Running through the GeoMoose install steps on a vanilla xubuntu 16.04, the bigger issue I see is it appears to be missing PHP Mapscript.

**Comment by johanvdw** [comment]
mapscript is not available on ubuntu 16.04, because php 7 is used (and
mapscript is not yet available).

**Comment by johanvdw** [comment]
See:
https://github.com/mapserver/mapserver/issues/5252


On Wed, Jun 1, 2016 at 8:21 PM, Johan Van de Wauw <johan.vandewauw@gmail.com

**Comment by klassenjs** [comment]
PHP7 missing MapScript discussion continues here: https://trac.osgeo.org/osgeo/ticket/1717

**Comment by kalxas** [comment]
This commit has already been merged in master:
https://github.com/OSGeo/OSGeoLive/commit/33664243d17f10ec0df7ea2892341d5cbf433f3a

**Pull request closed without merging**
