### PR TITLE
Refactor rasdaman install script to use the rasdaman installer

### PR DESCRIPTION
**Pull request by woland84**

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @woland84 I will include in next nightly and let you know

**Comment by kalxas** [comment]
@woland84 unfortunately you cloned the repo including some commits that were deleted in the meanwhile so your PR re-introduces them.
I can only cherry-pick your own commit and create a new PR

**Comment by woland84** [comment]
I can submit a new pull request, just one sec.

**Comment by kalxas** [comment]
@woland84 oops, sorry, I already did it...

**Comment by woland84** [comment]
no worries, thanks :)

**Pull request closed without merging**
