### PR TITLE
Update GeoNetwork to use js/css cache generated at compile/build time - v3.0.3

### PR DESCRIPTION
**Pull request by sppigot**

### CODE REVIEW

**Comment by kalxas** [comment]
Thank you @sppigot 
It will be tested right away on a new build

**Comment by kalxas** [comment]
Hi @sppigot 
The build including the commits of your pull request is here:
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-pr84-amd64-5ee2db9.iso
Logs:
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-pr84-amd64-5ee2db9-log.tar.gz

I was not able to start GeoNetwork with 4GB of RAM allocated on the VM.
Can you please have a look?

**Comment by kalxas** [comment]
Looking at the logs it seems that version 3.0.1 was pulled in again.
Perhaps there was a confusion in the branch name I gave to the build...

**Comment by kalxas** [comment]
Sorry, the iso provided above is a wrong rename of a previous build.
I will build again to be sure...

**Comment by kalxas** [comment]
@sppigot sorry for the delay, the iso to test is:
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-pr84-amd64-1b2aaf7.iso
Logs: http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-pr84-amd64-1b2aaf7-log.tar.gz
From my test, GN took 3.3GB and 3 mins to start up, but then the admin page did not appear.

**Comment by sppigot** [comment]
Sorry @kalxas - forgot to include updated settings for the 3.0.3 release. Should be fine now.

**Comment by kalxas** [comment]
Thanks, I will test and report back.

**Comment by sppigot** [comment]
Couple of extra commits added - hopefully that should do it - thanks @kalxas!

**Comment by kalxas** [comment]
Thanks @sppigot rebuilding...

**Comment by kalxas** [comment]
@sppigot still does not work...
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-pr84-amd64-fa1852a.iso
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-pr84-amd64-fa1852a-log.tar.gz

**Comment by sppigot** [comment]
Hmm - will investigate further - thanks.

**Comment by sppigot** [comment]
@kalxas - jai jars are still present - removing them fixes the problem. I added an rm -f for these to the geonetwork_install.sh - not sure why they are still present..... I'll check the logs.

**Comment by kalxas** [comment]
@sppigot thanks, I tried removing the jai files and it does work.
Lets see if the next build will be ok...

**Comment by kalxas** [comment]
New build logs:
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-pr84-amd64-67d7891-log.tar.gz

It seems the jai files are removed now.

**Comment by kalxas** [comment]
@sppigot I am testing the new iso:
The jai files are gone, thanks for that.
The first time I launched GN I got a 503 error.
I stopped the service and I noticed that jetty had started twice...
I manually stopped and started the service and it worked fine.

**Comment by kalxas** [comment]
I am going to merge now since the situation is much better that the 3.0.1 setup.
I will test again in the next nightly and report in the trac ticket.

**Comment by kalxas** [comment]
@sppigot any insights on the first lauch failure?
We are getting close to the release date....

**Comment by sppigot** [comment]
I haven't seen that problem @kalxas and I don't know of anything that has changed that would cause that. That said, I'll check and see if I can reproduce it again.

**Comment by kalxas** [comment]
Have you downloaded the latest iso?

**Comment by kalxas** [comment]
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-build151-amd64-81cad69.iso

**Comment by sppigot** [comment]
Checking now - thanks.

**Pull request merged**
