### PR TITLE
Update for MapProxy 1.8.0

### PR DESCRIPTION
**Pull request by olt**
Link to new deb files.

### CODE REVIEW

**Comment by johanvdw** [comment]
Hello Olivier,
Rather than downloading the debfile, I prefer adding it to our launchpad repository. Ideally, we should also aim for adding mapproxy to debian GIS.
I'm willing to help you with this. Is the package you provide based on the current Git status?

Kind Regards,
Johan

**Comment by johanvdw** [comment]
BTW: there is a strange thing in your install script: on line 76 you say Terminal should be True, but on line 86 you specify Terminal=False

**Comment by olt** [comment]
The .deb is built on the 1.8.x branch. There is a debian/ dir in MapProxy that I use for building these .deb files.
To be honest, I don't have any clue about launchpad and my resources for OSGeoLive are limited.


Re terminal=false: The comment was outdated. I've removed it.

**Comment by johanvdw** [comment]
I've built the package from the same tree at my testing repository:
https://launchpad.net/~johanvdw/+archive/ubuntu/osgeolive
Can you validate whether this package works well? Then I'll copy to our osgeolive repository and we can just use apt-get install --yes mapproxy.

**Comment by olt** [comment]
Yes, that package works! Thanks.

**Comment by kalxas** [comment]
@olt thanks for testing, can you please modify the installer to use the deb package?

**Comment by kalxas** [comment]
merged in https://github.com/OSGeo/OSGeoLive/commit/75ce84d3840c16781412be8b5d48d3a6b71a22ca

**Pull request closed without merging**
