### PR TITLE
Rasdaman demo webiste patch

### PR DESCRIPTION
**Pull request by vladmerti**
I added 2 sed commands after rasdaman is installed that replace some deprecated urls in the rasdaman demo website.

### CODE REVIEW

**Comment by kalxas** [comment]
@vladmerti will the rasdaman demo work when the disk is offline? 
I see that you are using a remote url in this patch.

One of the key features of OSGeo-Live is that it can be used without access to network.

**Comment by vladmerti** [comment]
Most of the demos yes. There are a couple, however, that require internet access, since the data was too big to put it in OSGeo Live. The user is notified if he lands on a page that requires internet access and he's offline.

**Comment by kalxas** [comment]
btw, I have tested the fix and works fine, thank you

**Comment by kalxas** [comment]
Thanks @vladmerti

**Comment by vladmerti** [comment]
No problem, thank you for providing guidance for setting up and reproducing.

**Pull request merged**
