### PR TITLE
FIxed config dir bug in ncWMS2 build

### PR DESCRIPTION
**Pull request by guygriffiths**
@kalxas - I think this should fix the issue with the incorrect config directory

### CODE REVIEW

**Comment by kalxas** [comment]
Hi @guygriffiths 
Your PR is including older commits.
I will cherry-pick only your last one.

**Comment by kalxas** [comment]
merged:
https://github.com/OSGeo/OSGeoLive/commit/9efb450b2cec4bb64e39547e8064807917f8d6de

**Comment by kalxas** [comment]
All working fine now @guygriffiths 
Thank you

**Comment by guygriffiths** [comment]
Excellent, good to hear it :)

**Pull request closed without merging**
