### PR TITLE
Upgrade OpenLayers 3 to 3.7.0

### PR DESCRIPTION
**Pull request by rdewit**
- Use the OL3 release files from GitHub instead of Debian package

### CODE REVIEW

**Comment by kalxas** [comment]
thanks @rdewit 
@johanvdw is there any chance we can have a deb for this version? :)

**Comment by johanvdw** [comment]
Perhaps it is better to use the zipfile for openlayers here. I prefer
spending time packaging things which can actually go into debian later on.
It shouldn't be hard though.

Kind Regards,
Johan

**Comment by kalxas** [comment]
Cool, I am building an iso to test now and will merge if things are smooth

**Comment by kalxas** [comment]
merged on https://github.com/OSGeo/OSGeoLive/commit/deef69a6e8f477c02c18736b1d710063c18b7943

**Pull request closed without merging**
