### PR TITLE
Update ncWMS to 2.2.8

### PR DESCRIPTION
**Pull request by guygriffiths**

### CODE REVIEW

**Comment by kalxas** [comment]
Unfortunately the PR did not work as expected in the build.
Here is the build log:
```
===============================================================
Starting "install_ncWMS.sh" ...
===============================================================
[23:17]: ncWMS2 install started
TMP: /tmp/build_ncWMS
USER_NAME: user
USER_HOME: /home/user
TOMCAT_USER_NAME: tomcat8
WMS_WAR_INSTALL_DIR: /var/lib/tomcat8/webapps
WMS_TAR_URL: 
WMS_WEB_APP_NAME: ncWMS2
WMS_TOMCAT_SCRIPT_NAME: tomcat8
WMS_ICON_NAME: ncWMS_icon.png
WMS_URL: http://localhost:8080/ncWMS2
WMS_QUICKSTART_URL: http://localhost/osgeolive/en/quickstart/ncWMS_quickstart.html
WMS_OVERVIEW_URL: http://localhost/osgeolive/en/overview/ncWMS_overview.html
[23:17]: tomcat8 service script found in /etc/init.d/.
http://: Invalid host name.
cp: cannot stat '../app-conf/ncwms/ncWMS_icon.png': No such file or directory
chmod: cannot access '/usr/local/share/icons/ncWMS_icon.png': No such file or directory
mv: cannot stat '/tmp/build_ncWMS/ncWMS2.war': No such file or directory
chown: cannot access '/var/lib/tomcat8/webapps/ncWMS2.war': No such file or directory
failed to change ownership of '/var/lib/tomcat8/webapps/ncWMS2.war' to tomcat8:tomcat8
[23:17]: ncWMS2 installed in tomcat webapps folder
mkdir: created directory '/usr/share/tomcat8/.ncWMS'
cp: cannot stat '../app-conf/ncwms/config.xml': No such file or directory
chmod: cannot access '/usr/share/tomcat8/.ncWMS2/config.xml': No such file or directory
chown: cannot access '/usr/share/tomcat8/.ncWMS2': No such file or directory
failed to change ownership of '/usr/share/tomcat8/.ncWMS2' to tomcat8:tomcat8
'/usr/local/share/applications/ncWMS-start.desktop' -> '/home/user/Desktop/ncWMS-start.desktop'
changed ownership of '/home/user/Desktop/ncWMS-start.desktop' from root:root to user:user
'/usr/local/share/applications/ncWMS-stop.desktop' -> '/home/user/Desktop/ncWMS-stop.desktop'
changed ownership of '/home/user/Desktop/ncWMS-stop.desktop' from root:root to user:user
```
You can download the result iso here: http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-build46-amd64-7fa7848.iso

**Comment by guygriffiths** [comment]
Ah OK, I didn't spot that I'd changed to the build directory first.  This latest commit should fix that...

**Comment by kalxas** [comment]
Thanks, I will try again.

**Comment by kalxas** [comment]
Still not fixed:
```
===============================================================
Starting "install_ncWMS.sh" ...
===============================================================
[42:45]: ncWMS2 install started
TMP: /tmp/build_ncWMS
USER_NAME: user
USER_HOME: /home/user
TOMCAT_USER_NAME: tomcat8
WMS_WAR_INSTALL_DIR: /var/lib/tomcat8/webapps
WMS_WEB_APP_NAME: ncWMS2
WMS_TOMCAT_SCRIPT_NAME: tomcat8
WMS_ICON_NAME: ncWMS_icon.png
WMS_URL: http://localhost:8080/ncWMS2
WMS_QUICKSTART_URL: http://localhost/osgeolive/en/quickstart/ncWMS_quickstart.html
WMS_OVERVIEW_URL: http://localhost/osgeolive/en/overview/ncWMS_overview.html
[42:45]: tomcat8 service script found in /etc/init.d/.
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2017-06-08 12:42:45--  http://ncwms2.war/
Resolving ncwms2.war (ncwms2.war)... failed: Name or service not known.
wget: unable to resolve host address 'ncwms2.war'
'../app-conf/ncwms/ncWMS_icon.png' -> '/usr/local/share/icons/ncWMS_icon.png'
'/tmp/build_ncWMS/ncWMS2.war' -> '/var/lib/tomcat8/webapps/ncWMS2.war'
changed ownership of '/var/lib/tomcat8/webapps/ncWMS2.war' from root:root to tomcat8:tomcat8
[42:46]: ncWMS2 installed in tomcat webapps folder
mkdir: created directory '/usr/share/tomcat8/.ncWMS'
'../app-conf/ncwms/config.xml' -> '/usr/share/tomcat8/.ncWMS2/config.xml'
cp: cannot create regular file '/usr/share/tomcat8/.ncWMS2/config.xml': No such file or directory
chmod: cannot access '/usr/share/tomcat8/.ncWMS2/config.xml': No such file or directory
chown: cannot access '/usr/share/tomcat8/.ncWMS2': No such file or directory
failed to change ownership of '/usr/share/tomcat8/.ncWMS2' to tomcat8:tomcat8
'/usr/local/share/applications/ncWMS-start.desktop' -> '/home/user/Desktop/ncWMS-start.desktop'
changed ownership of '/home/user/Desktop/ncWMS-start.desktop' from root:root to user:user
'/usr/local/share/applications/ncWMS-stop.desktop' -> '/home/user/Desktop/ncWMS-stop.desktop'
changed ownership of '/home/user/Desktop/ncWMS-stop.desktop' from root:root to user:user
```

**Comment by guygriffiths** [comment]
OK, I see the typo that's caused that, and fixed it.

However, do you have any advice on how to test this?  Running it on my own system is no good - as well as not wanting to install anything over my existing installations, my system is not set up the same.  Effectively I'm having to trust both my shell scripting and my accurate reading abilities, neither of which I really do trust!

**Comment by kalxas** [comment]
I would recommend testing on an empty Xenial VM, after using bootstrap.sh to set the directory structure.
The best way to test though is to build an iso.
https://wiki.osgeo.org/wiki/Live_GIS_Build#How_to_do_development_.2F_debugging_with_the_current_build_method

I will keep doing nightly builds on daily basis, so at some point we will get it right :)

**Comment by kalxas** [comment]
The installation succeeded this time, but the list on the left is empty and reports no datasets found.

**Comment by kalxas** [comment]
```
'../app-conf/ncwms/ncWMS_icon.png' -> '/usr/local/share/icons/ncWMS_icon.png'
'/tmp/build_ncWMS/ncWMS2.war' -> '/var/lib/tomcat8/webapps/ncWMS2.war'
changed ownership of '/var/lib/tomcat8/webapps/ncWMS2.war' from root:root to tomcat8:tomcat8
[47:40]: ncWMS2 installed in tomcat webapps folder
mkdir: created directory '/usr/share/tomcat8/.ncWMS'
'../app-conf/ncwms/config.xml' -> '/usr/share/tomcat8/.ncWMS2/config.xml'
cp: cannot create regular file '/usr/share/tomcat8/.ncWMS2/config.xml': No such file or directory
chmod: cannot access '/usr/share/tomcat8/.ncWMS2/config.xml': No such file or directory
chown: cannot access '/usr/share/tomcat8/.ncWMS2': No such file or directory
failed to change ownership of '/usr/share/tomcat8/.ncWMS2' to tomcat8:tomcat8
'/usr/local/share/applications/ncWMS-start.desktop' -> '/home/user/Desktop/ncWMS-start.desktop'
changed ownership of '/home/user/Desktop/ncWMS-start.desktop' from root:root to user:user
'/usr/local/share/applications/ncWMS-stop.desktop' -> '/home/user/Desktop/ncWMS-stop.desktop'
changed ownership of '/home/user/Desktop/ncWMS-stop.desktop' from root:root to user:user
```

**Comment by kalxas** [comment]
should the folder be ```/usr/share/tomcat8/.ncWMS2/``` or ```/usr/share/tomcat8/.ncWMS/``` ?

**Comment by kalxas** [comment]
I have manually merged to master.
Please review my last commit:
https://github.com/OSGeo/OSGeoLive/commit/22371ef201748bb530f5615af233e554d32f5ac6

**Comment by kalxas** [comment]
Unfortunately, after my fix, I still get the message "no datasets found"

**Comment by kalxas** [comment]
I am closing this, since it was merged.
@guygriffiths please open a new pull request for the fix.

**Comment by guygriffiths** [comment]
@kalxas - It should be /usr/share/tomcat8/.ncWMS2

I couldn't find where any of the datasets were located, so I used the same config file as was used for ncWMS 1.2.  Are there still data files in /usr/local/share/data/netcdf/?  Where can I find a list of what is in there?

**Comment by kalxas** [comment]
ok thanks, I will fix by merging your new PR.
Here is a list of the data:
```
user@osgeolive:/usr/local/share/data/netcdf$ ls
README_netCDF_samples.txt
rx5dayETCCDI_yr_MIROC5_historical_r2i1p1_1850-2012.nc
rx5dayETCCDI_yr_MIROC5_historical_r2i1p1_1850-2012.nc.txt
rx5dayETCCDI_yr_MIROC5_rcp45_r2i1p1_2006-2100.nc
rx5dayETCCDI_yr_MIROC5_rcp45_r2i1p1_2006-2100.nc.txt
txxETCCDI_yr_MIROC5_historical_r2i1p1_1850-2012.nc
txxETCCDI_yr_MIROC5_historical_r2i1p1_1850-2012.nc.txt
txxETCCDI_yr_MIROC5_rcp45_r2i1p1_2006-2100.nc
txxETCCDI_yr_MIROC5_rcp45_r2i1p1_2006-2100.nc.txt
```

**Pull request closed without merging**
