### PR TITLE
Update 52nSOS to latest version 4.3.0 (requires tomcat7)

### PR DESCRIPTION
**Pull request by EHJ-52n**
Update installation script to install latest version of SOS.

This **requires** tomcat 7, hence OSGeo/OSGeoLive/pull/5 should be merged before merging this. If not, we have tomcat 6 and 7 installed.

### CODE REVIEW

**Comment by kalxas** [comment]
@EHJ-52n we need to rebase or cherry-pick your last 3 commits on top of current master.

**Comment by EHJ-52n** [comment]
@kalxas should I merge this with the latest version of osgeo:master?

**Comment by kalxas** [comment]
@EHJ-52n I would recommend to rebase or cherry-pick your changes

**Comment by EHJ-52n** [comment]
@kalxas what do you mean. Should I update my branch to the latest version?

**Comment by kalxas** [comment]
@EHJ-52n I will cherry pick what is needed in order to keep master history clean
thanks.

**Comment by kalxas** [comment]
cherry-picked here:
https://github.com/kalxas/OSGeoLive/commits/52nsos

**Comment by kalxas** [comment]
I will now start a new nightly

**Comment by kalxas** [comment]
Build logs:
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-build57-amd64-b0a4a05-log.tar.gz

**Comment by kalxas** [comment]
Confirmed working in nightly build. Merged in master now

**Pull request closed without merging**
